name: fsh
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2025.2.25=h06a4308_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libxcb=1.17.0=h9b100fa_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.16=h5eee18b_0
  - pip=24.2=py38h06a4308_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.8.20=he870216_0
  - readline=8.2=h5eee18b_0
  - sqlite=3.50.2=hb25bd0a_1
  - tk=8.6.14=h993c535_1
  - wheel=0.44.0=py38h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - absl-py==1.4.0
      - addict==2.4.0
      - anyio==4.5.2
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==21.2.0
      - array-record==0.4.0
      - arrow==1.3.0
      - asttokens==3.0.0
      - astunparse==1.6.3
      - async-lru==2.0.4
      - attrs==25.3.0
      - babel==2.17.0
      - backcall==0.2.0
      - beautifulsoup4==4.13.4
      - bleach==6.1.0
      - blinker==1.8.2
      - cached-property==1.5.2
      - cachetools==5.5.0
      - ccimport==0.4.4
      - certifi==2022.12.7
      - cffi==1.17.1
      - charset-normalizer==3.4.0
      - click==8.1.8
      - cloudpickle==3.1.1
      - comm==0.2.2
      - configargparse==1.7
      - contourpy==1.1.1
      - cumm-cu116==0.4.11
      - cycler==0.11.0
      - dacite==1.8.1
      - dash==3.0.3
      - dask==2023.3.1
      - dataclass-array==1.4.1
      - debugpy==1.8.15
      - decorator==5.2.1
      - defusedxml==0.7.1
      - descartes==1.1.0
      - dm-tree==0.1.8
      - easydict==1.13
      - einops==0.6.1
      - einsum==0.3.0
      - etils==1.3.0
      - exceptiongroup==1.3.0
      - executing==2.2.0
      - fastjsonschema==2.21.1
      - filelock==3.12.2
      - fire==0.7.0
      - flask==3.0.3
      - flatbuffers==25.2.10
      - fonttools==4.57.0
      - fqdn==1.5.1
      - fsspec==2025.3.0
      - gast==0.4.0
      - google-auth==2.16.2
      - google-auth-oauthlib==0.4.6
      - google-pasta==0.2.0
      - googleapis-common-protos==1.63.1
      - grpcio==1.70.0
      - h11==0.16.0
      - h5py==3.1.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - idna==3.10
      - imageio==2.35.1
      - immutabledict==2.2.0
      - importlib-metadata==8.4.0
      - importlib-resources==6.4.5
      - ipykernel==6.29.5
      - ipython==8.12.3
      - ipywidgets==8.1.6
      - isoduration==20.11.0
      - itsdangerous==2.2.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.4.2
      - json5==0.12.0
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - jupyter==1.1.1
      - jupyter-client==8.6.3
      - jupyter-console==6.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.6
      - jupyter-server==2.14.2
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.3.8
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.14
      - keras==2.11.0
      - keras-preprocessing==1.1.2
      - kiwisolver==1.4.7
      - lark==1.1.9
      - lazy-loader==0.4
      - libclang==18.1.1
      - llvmlite==0.31.0
      - locket==1.0.0
      - markdown==3.4.4
      - markupsafe==2.1.5
      - matplotlib==3.6.1
      - matplotlib-inline==0.1.7
      - mistune==3.1.3
      - motmetrics==1.4.0
      - narwhals==1.35.0
      - navsim==2.8.0
      - nbclient==0.10.1
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.1
      - ninja==1.11.1.1
      - notebook==7.3.3
      - notebook-shim==0.2.4
      - numba==0.48.0
      - numpy==1.21.5
      - nuscenes-devkit==1.0.5
      - oauthlib==3.2.2
      - open3d==0.18.0
      - opencv-python==4.10.0.84
      - openexr==1.3.9
      - opt-einsum==3.3.0
      - overrides==7.7.0
      - packaging==24.0
      - pandas==1.5.3
      - pandocfilters==1.5.1
      - parso==0.8.4
      - partd==1.4.1
      - pccm==0.4.16
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pillow==9.2.0
      - pkgutil-resolve-name==1.3.10
      - platformdirs==4.3.6
      - plotly==5.13.1
      - portalocker==3.0.0
      - prometheus-client==0.21.1
      - promise==2.3
      - prompt-toolkit==3.0.51
      - protobuf==3.19.6
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyarrow==10.0.0
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pybind11==2.13.6
      - pycparser==2.22
      - pygments==2.19.1
      - pyparsing==3.1.4
      - pyquaternion==0.9.9
      - python-dateutil==2.9.0.post0
      - python-json-logger==3.3.0
      - pytz==2025.2
      - pywavelets==1.3.0
      - pyyaml==6.0.1
      - pyzmq==27.0.0
      - referencing==0.35.1
      - requests==2.31.0
      - requests-oauthlib==2.0.0
      - retrying==1.3.4
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.20.1
      - rsa==4.9
      - scikit-image==0.20.0
      - scikit-learn==1.2.2
      - scipy==1.9.1
      - send2trash==1.8.3
      - setuptools==67.6.0
      - shapely==2.0.7
      - sharedarray==3.0.0
      - six==1.15.0
      - sniffio==1.3.1
      - soupsieve==2.7
      - spconv-cu116==2.3.6
      - stack-data==0.6.3
      - tenacity==9.0.0
      - tensorboard==2.11.2
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorboardx==2.4
      - tensorflow==2.11.0
      - tensorflow-addons==0.21.0
      - tensorflow-datasets==4.9.0
      - tensorflow-estimator==2.11.0
      - tensorflow-graphics==2021.12.3
      - tensorflow-io-gcs-filesystem==0.34.0
      - tensorflow-metadata==1.13.0
      - tensorflow-probability==0.19.0
      - termcolor==1.1.0
      - terminado==0.18.1
      - threadpoolctl==3.5.0
      - tifffile==2021.11.2
      - tinycss2==1.2.1
      - toml==0.10.2
      - tomli==2.2.1
      - toolz==1.0.0
      - torch==1.13.1+cu116
      - torch-scatter==2.1.1
      - torchaudio==0.13.1+cu116
      - torchvision==0.14.1+cu116
      - tornado==6.4.2
      - tqdm==4.66.5
      - traitlets==5.14.3
      - trimesh==4.6.8
      - triton==2.1.0
      - typeguard==2.13.3
      - types-python-dateutil==2.9.0.20241206
      - typing-extensions==4.13.2
      - tzdata==2025.2
      - uri-template==1.3.0
      - urllib3==2.0.7
      - visu3d==1.5.1
      - waymo-open-dataset-tf-2-11-0==1.6.1
      - wcwidth==0.2.13
      - webcolors==24.8.0
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - werkzeug==3.0.6
      - widgetsnbextension==4.0.14
      - wrapt==1.12.1
      - xmltodict==0.14.2
      - zipp==3.15.0
prefix: /root/packages/anconda3/envs/fsh
